sudo: required
services: 
  - docker

before_install:
  - docker build -t nibrasmuhamed/react-docker -f Dockerfile.dev .

script:
  - docker run nibrasmuhamed/react-docker npm run test -- --coverage
  
